version: '3.4'

services:
  easy_diffusion:
    build:
      context: ./
      dockerfile: ./Dockerfile
    tty: true
    working_dir: /app/easy-diffusion
    # volumes:
    #   - ../:/app
    env_file:
      - ./.env
    # command: ./start.sh