version: '3.4'

services:
  python-to-cpp:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    tty: true
    working_dir: /app
    # volumes:
    #   - ../:/app
    env_file:
      - ./.env
    command:
      - /bin/bash
      - -c
      - |
        ./start.sh